.pragma library

var UI_HEADER_HEIGHT    =   73;
var UI_HEADER_COLOR     =   "#cc8800";
var UI_HEADER_TITLE_FONT_SIZE = 28;
var UI_HEADER_SUBTITLE_FONT_SIZE = 22;

var UI_DETAILS_TITLE_FONT_SIZE = 32
var UI_DETAILS_SUBTITLE_FONT_SIZE = 28;
var UI_DETAILS_DESC_FONT_SIZE = 25;

var UI_RESULTVIEW_TITLE_FONT_SIZE = 25;
var UI_RESULTVIEW_SUBTITLE_FONT_SIZE = 23;
var UI_RESULTVIEW_EXTRATEXT_FONT_SIZE = 20;

var UI_SEARCHBAR_ADVSEARCH_FONT_SIZE = 20;
var UI_LINE_HEIGHT = 3;
var UI_TEXTFIELD_LABEL_PERCENTAGE_WIDTH = 25;
var UI_ERROR_TEXT_FONTSIZE = 25;
