.pragma library

var UI_HEADER_HEIGHT    =   73;
var UI_HEADER_COLOR     =   "#cc8800";
var UI_HEADER_TITLE_FONT_SIZE = 28;
var UI_HEADER_SUBTITLE_FONT_SIZE = 22;

var UI_DETAILS_TITLE_FONT_SIZE = 32
var UI_DETAILS_SUBTITLE_FONT_SIZE = 28;
var UI_DETAILS_DESC_FONT_SIZE = 25;

var UI_RESULTVIEW_TITLE_FONT_SIZE = 25;
var UI_RESULTVIEW_SUBTITLE_FONT_SIZE = 23;
var UI_RESULTVIEW_EXTRATEXT_FONT_SIZE = 20;

var UI_SEARCHBAR_ADVSEARCH_FONT_SIZE = 20;
var UI_TEXTFIELD_LABEL_PERCENTAGE_WIDTH = 25;
var UI_ERROR_TEXT_FONTSIZE = 25;

var UI_CONTENT_TEXT_COLOR = "grey";
var UI_DEFAULT_LEFTRIGHT_MARGIN = 10;
var UI_DEFAULT_LIST_SPACING = 5;
var UI_DEFAULT_LISTITEM_SPACING = 3;

var UI_VIEWED_FLAG_WIDTH = 5;
var UI_VIEWED_FLAG_COLOR = "blue";

// line seperator
var UI_LINE_HEIGHT = 3;
var UI_LINE_COLOR  = "grey";

// icons
var UI_DEFAULT_LISTICON_SIZE = 64;
var UI_QUICKLAUNCH_BKG_SIZE = 80;
var UI_QUICKLAUNCH_ICON_SIZE = 52;

// Mainpage
var UI_ALERTUPDATES_FONT_SIZE = 30;
var UI_QUICKLAUNCH_FONT_SIZE = 22;

// logo
var UI_LOGO_WIDTH = 30;

// alert updates
var UI_ALERTUPDATES_NEWJOBCOUNT_FONT_SIZE = 33;
var UI_ALERTUPDATES_NEWJOBCOUNT_COLOR = "white";
