.pragma library

var UI_LOGO             = "qrc:/images/logo.svg";
var UI_HEADER_HEIGHT    =   73;
var UI_HEADER_COLOR     =   "#309dcf";
var UI_HEADER_TITLE_FONT_SIZE = 27;
var UI_HEADER_SUBTITLE_FONT_SIZE = 20;
var UI_HEADER_TITLE_COLOR = "white";
var UI_HEADER_SUBTITLE_COLOR = "white";
var UI_HEADER_BUSYINDICATOR_SIZE = 50;

// loading screen
var UI_LOADINGSCREEN_FONT_SIZE = 60;
var UI_LOADINGSCREEN_BUSYINDICATOR_WIDTH = 30;
var UI_LOADINGSCREEN_LOGO_WIDTH = 200;
var UI_LOADINGSCREEN_LOGO_HEIGHT = 400;

var UI_RESULTVIEW_TITLE_FONT_SIZE = 25;
var UI_RESULTVIEW_SUBTITLE_FONT_SIZE = 23;
var UI_RESULTVIEW_EXTRATEXT_FONT_SIZE = 20;
var UI_RESULTVIEW_CONTENT_FONT_SIZE = 25;
var UI_RESULTVIEW_EXTRATEXT_COLOR = "grey";

var UI_SEARCHBAR_ADVSEARCH_FONT_SIZE = 20;
var UI_TEXTFIELD_LABEL_PERCENTAGE_WIDTH = 25;
var UI_ERROR_TEXT_FONTSIZE = 30;

var UI_CONTENT_TEXT_COLOR = "grey";
var UI_DEFAULT_LEFTRIGHT_MARGIN = 10;
var UI_DEFAULT_LIST_SPACING = 5;
var UI_DEFAULT_COMPACTLIST_SPACING = 10;
var UI_DEFAULT_LISTITEM_SPACING = 3;
var UI_DEFAULT_COMPACTLISTITEM_SPACING = 6;

var UI_VIEWED_FLAG_WIDTH = 5;
var UI_VIEWED_FLAG_COLOR = "blue";

// line seperator
var UI_LINE_HEIGHT = 1;
var UI_LINE_MARGIN = 10;
var UI_LINE_COLOR  = "white";
var UI_LINE_BORDER_COLOR = "grey";

// icons
var UI_DEFAULT_LISTICON_SIZE = 64;
var UI_QUICKLAUNCH_BKG_SIZE = 80;
var UI_QUICKLAUNCH_ICON_SIZE = 52;
var UI_FAVJOB_SMALL_SIZE = 32;
var UI_FAVJOB_ICON = "qrc:/images/favoritejob.svg";

// toolbar icons
var UI_TOOLICON_BACK = "toolbar-back";
var UI_TOOLICON_DELETE = "toolbar-delete";
var UI_TOOLICON_FAV    = "toolbar-favorite-mark";
var UI_TOOLICON_ADDALERT = "toolbar-add";
var UI_TOOLICON_MENU     = "toolbar-view-menu";

// Mainpage
var UI_ALERTUPDATES_FONT_SIZE = 25;
var UI_QUICKLAUNCH_FONT_SIZE = 22;

// logo
var UI_LOGO_WIDTH = 30;

// alert updates
var UI_ALERTUPDATES_NEWJOBCOUNT_FONT_SIZE = 33;
var UI_ALERTUPDATES_NEWJOBCOUNT_COLOR = "white";
